### ISSUE TITLE
Load Local Storage?

### ISSUE THREAD

**Issue by chobo2** [capaj/mobx-stored#8]
Hi

```
const defaultUser = { email: null, firstname: null, lastname: null }
const observableUserProfile = localStored('userProfile', defaultUser, {
  delay: 500
}) // last parameter is optional-mobx autorn options for running the save operation into the storage. Use higher delay if you store a lot of data
```
this is fine for the first time around, but when the user comes back I don't want to reset a defaultUser as it was already set the last time around.

**Comment by capaj** [comment]
hey @chobo2 sorry for late answer, but this is not a problem because the default is always extended with the data in the localStorage. Will ammend a readme.
